version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.12"
      MODE: "SURVIVAL"
      ONLINE_MODE: "FALSE"
